name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check code formatting
      run: |
        npm run lint || (echo "::error::Linting failed. Please run 'npm run lint' locally and fix issues." && exit 1)
    
    - name: Check TypeScript
      run: |
        npm run type-check || (echo "::error::Type checking failed. Please fix TypeScript errors." && exit 1)
    
    - name: Run tests with coverage
      run: npm test -- --run --coverage
    
    - name: Coverage Report Comment
      uses: romeovs/lcov-reporter-action@v0.3.1
      if: github.event_name == 'pull_request'
      with:
        lcov-file: ./coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        title: "Test Coverage Report"
    
    - name: Check coverage decrease
      run: |
        # This script checks if coverage has decreased
        echo "Checking coverage thresholds..."
        npm test -- --run --coverage.thresholdAutoUpdate=false || (echo "::error::Coverage has decreased below thresholds. Please add tests." && exit 1)
    
    - name: Bundle size check
      run: |
        npm run build
        echo "Build size report:"
        du -sh dist/
        find dist -name "*.js" -o -name "*.css" | xargs ls -lh
    
    - name: Check for console logs
      run: |
        # Check for console.log statements in source code
        if grep -r "console\.log" --include="*.ts" --include="*.tsx" src/ --exclude-dir=__tests__ --exclude-dir=tests; then
          echo "::warning::Found console.log statements. Please remove them before merging."
        fi
    
    - name: Security audit
      run: |
        npm audit --production || echo "::warning::Security vulnerabilities found. Please review npm audit report."
    
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --run
    
    - name: Build check
      run: npm run build