version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/scorm-builder"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      tauri:
        patterns:
          - "@tauri-apps/*"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@vitejs/*"
          - "vite*"
          - "typescript"

  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/scorm-builder/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5