name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: scorm-builder/package-lock.json
      
      - name: Install dependencies
        working-directory: ./scorm-builder
        run: npm ci
      
      - name: Run TypeScript type check
        working-directory: ./scorm-builder
        run: npx tsc --noEmit
      
      - name: Check for build errors
        working-directory: ./scorm-builder
        run: npm run build

  rust-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './scorm-builder/src-tauri -> target'
      
      - name: Check formatting
        working-directory: ./scorm-builder/src-tauri
        run: cargo fmt -- --check
      
      - name: Run clippy
        working-directory: ./scorm-builder/src-tauri
        run: cargo clippy -- -D warnings
      
      - name: Run tests
        working-directory: ./scorm-builder/src-tauri
        run: cargo test